name: robot2_domain_bridge
from_domain: 11
to_domain: 1

topics:
  /robot_2/soldier_pose:
    type: geometry_msgs/msg/PoseWithCovarianceStamped

  /robot_2/odom:
    type: nav_msgs/msg/Odometry

  /robot_2/battery_state:
    type: sensor_msgs/msg/BatteryState

  /robot_2/cmd_vel:
    type: geometry_msgs/msg/Twist
    reversed: true

  /robot_2/goal_pose:
    type: geometry_msgs/msg/PoseStamped
    reversed: true

  /robot_2/initialpose:
    type: geometry_msgs/msg/PoseWithCovarianceStamped
    reversed: true
